### ISSUE TITLE
Oracle XE images

### ISSUE THREAD

**Issue by bit-man** [oracle/docker#17]
Even that there's some Oracle XE images available at docker (wnameless/oracle-xe-11g and others) would be nice to have the Oracle official docker stuff

**Comment by Djelibeybi** [comment]
Those images contravene the Oracle license for XE and should not be used.

**Comment by brunoborges** [comment]
@bit-man as Avi said, those images are not in accordance to the license. But we will work with the Oracle DB product team and see if we can come up with a solution for this. Anyway, thanks a lot for showing interest in an official Dockerfile for Oracle DB. We'll keep you and the community posted.

**Comment by bit-man** [comment]
Thanks for taking care.
