### ISSUE TITLE
Weblogic 12c image commEnv.sh has DOS CRLF end of line terminators

### ISSUE THREAD

**Issue by kevinhooke** [oracle/docker#18]
When you start the Weblogic 12c image, /u01/oracle/wls12130/wlserver/common/bin/commEnv.sh fails with errors:

./commEnv.sh: line 4: $'\r': command not found
./commEnv.sh: line 18: syntax error: unexpected end of file

indicating it's in dos format. If you replace the \r\n end of lines then it's fine.

Not sure if this is an issue with the image, the dockerfile script, or did I use the wrong downloads to create my image including Weblogic?

**Comment by brunoborges** [comment]
@kevinhooke what environment is yours?

**Comment by kevinhooke** [comment]
I'm running Docker on Vagrant on Windows 7 with a chef/centos-7.0 box, attempting to run WLS 12.1.3 on the oraclelinux:7 base image, per the Dockerfile from here. Should I try a different OS box on Vagrant? Any suggestions?

**Comment by brunoborges** [comment]
Try building the image from scratch, but on a regular VirtualBox CentOS machine. If that works, it should work through Vagrant. If it doesn't work, then it's something related to Docker on CentOS.

FYI, we don't certify at this moment WebLogic inside a Docker container running on a host any different than Red Hat or Oracle Linux.

**Comment by kevinhooke** [comment]
Thanks, I'll give that a try in the next day or so and report back.

**Comment by brunoborges** [comment]
@kevinhooke did it work? Also, if you checkout the code using a proper Git client on Windows, the CRLF is fixed automatically

**Comment by brunoborges** [comment]
This is not a problem with the source code, but how code is checked out into Windows environments.

**Comment by gordontyler** [comment]
You should be using .gitattributes in your repo to force .sh files to use eol-LF.

**Comment by brunoborges** [comment]
@gordontyler would you be kind to send a PR ?

**Comment by gordontyler** [comment]
Done: #29

**Comment by brunoborges** [comment]
Thanks a lot @gordontyler !
