### ISSUE TITLE
oraclelinux:7 error 404 but 7.0 works

### ISSUE THREAD

**Issue by maniankara** [oracle/docker#19]
Hi,
----------------- clip -----------------
Unable to find image 'oraclelinux:7' locally
Pulling repository oraclelinux
8a2b759d9dd8: Error pulling image (7) from oraclelinux, HTTP code 400 
8c3e49cb06dc: Download complete 
90fed8b1ceab: Error pulling dependent layers 
FATA[0014] Error pulling image (7) from oraclelinux, HTTP code 400 
----------------- clip -----------------

Thanks,
 - Anoop

**Comment by Djelibeybi** [comment]
This is an issue with the Docker Hub Registry, not our image. Please log a bug with Docker themselves. I'm travelling today and tomorrow, so I can't log it properly myself.
