### ISSUE TITLE
Impossible to pull image from docker repository

### ISSUE THREAD

**Issue by AlexanderShniperson** [oracle/docker#20]
coreos01 core # docker pull oraclelinux
Pulling repository oraclelinux
8a2b759d9dd8: Error pulling image (latest) from oraclelinux, HTTP code 400 
8c3e49cb06dc: Download complete 
90fed8b1ceab: Error pulling dependent layers 
FATA[0078] Error pulling image (latest) from oraclelinux, HTTP code 400

**Comment by Djelibeybi** [comment]
This is an upstream issue on the Docker Hub. I'll log an issue there. It may take a while to fix, given that everyone is at Dockercon today.

**Comment by Djelibeybi** [comment]
https://github.com/docker-library/official-images/issues/844

Note that I can't reproduce this issue on Oracle Linux 6 using Docker 1.6.1.

**Comment by Djelibeybi** [comment]
Note that neither the Docker team nor I can reproduce this. If it happens again, please log a direct request with Docker at http://support.docker.com so they can ask for more detailed logs.
