### ISSUE TITLE
Impossible to load image

### ISSUE THREAD

**Issue by AlexanderShniperson** [oracle/docker#21]
coreos01 core # docker load -i /tmp/oraclelinux-7.1.tar.xz 
FATA[0005] Error response from daemon: open /var/lib/docker/tmp/docker-import-913281699/repo/boot/json: no such file or directory

i am on CoreOS 695.2.0

**Comment by Djelibeybi** [comment]
You can't load the oraclelinux-7.1.tar.gz, it's not an export, it's a root filesystem. You need to use the associated Dockerfile and build FROM it.
