### ISSUE TITLE
Unable to run on OSX 

### ISSUE THREAD

**Issue by anupdugar** [oracle/docker#25]
I tried following steps in https://github.com/oracle/docker/tree/master/OracleWebLogic but i am not able to create the image. 
Had to fix : https://github.com/oracle/docker/blob/master/OracleWebLogic/dockerfiles/buildDockerImage.sh to use md5 instead of md5sum

It creates an image for oraclelinux but not for oracle/weblogic:12.1.3 as expected.

Here's the log from my run:
```
Checking if required packages are present and valid...
MD5 (Checksum.generic) = 21027d0cc2cd80d126f6ecf3f7b98e84
=====================
Building image 'oracle/weblogic:12.1.3' based on 'generic' distribution...
Sending build context to Docker daemon 18.43 kB
Sending build context to Docker daemon 
Step 0 : FROM oraclelinux:7
 ---> 8a2b759d9dd8
Step 1 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in 6295da1b6ce8
 ---> d6ffde8e55b4
Removing intermediate container 6295da1b6ce8
Step 2 : ENV JAVA_RPM jdk-7u79-linux-x64.rpm
 ---> Running in 0ca160590b0a
 ---> 4b60836085b3
Removing intermediate container 0ca160590b0a
Step 3 : ENV WLS_PKG fmw_12.1.3.0.0_wls.jar
 ---> Running in 125be5b503ad
 ---> 6cbf0b58dadb
Removing intermediate container 125be5b503ad
Step 4 : ENV JAVA_HOME /usr/java/default
 ---> Running in 0a72ed658d37
 ---> ec49b9eb16f5
Removing intermediate container 0a72ed658d37
Step 5 : ENV CONFIG_JVM_ARGS -Djava.security.egd=file:/dev/./urandom
 ---> Running in 1e3b654bc554
 ---> 00480a0c4198
Removing intermediate container 1e3b654bc554
Step 6 : RUN mkdir /u01 &&     chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle
 ---> Running in 2ebc0661ba5a
 ---> cf7081431f9b
Removing intermediate container 2ebc0661ba5a
Step 7 : COPY $WLS_PKG /u01/
fmw_12.1.3.0.0_wls.jar: no such file or directory

WebLogic Docker Image for 'generic' 12.1.3 is ready to be extended: oracle/weblogic:12.1.3

**Comment by Djelibeybi** [comment]
Have you downloaded the fmw_12.1.3.0.0_wls.jar  file as per the instructions here: https://github.com/oracle/docker/blob/master/OracleWebLogic/dockerfiles/12.1.3/fmw_12.1.3.0.0_wls.jar.download

**Comment by anupdugar** [comment]
@Djelibeybi No, i havn't tried it. But i was hoping that i could reuse the image to setup weblogic without the need to explicitly download.

**Comment by Djelibeybi** [comment]
You can't use the image without downloading the Fusion Middleware, WebLogic and Java components first. These components cannot be shipped on GitHub and must be downloaded directly from Oracle so that you can accept the license terms.

Once you have the components in place, you can create an inital image and save it so that creating new images becomes instant.
