### ISSUE TITLE
image oraclelinux not fit for production ?

### ISSUE THREAD

**Issue by wkoertgen** [oracle/docker#28]
#### ulimit -Hn is 4096 and cannot be increased

[root@bdb014068c11 tmp]# ulimit -Hn 65536
bash: ulimit: open files: cannot modify limit: Operation not permitted

Oracle needs ulimit -Hn 65536. 

For the details please see http://wkoertgen.blogspot.de/2015/09/docker-oracle-rdbms-server-12cr1.html.

For training purposes as e.g. https://github.com/wkoertgen/train.docker.dataguard it is not crucial, but the relevance of data virtualisation is zero, if Oracle is not willing or able to deliver productive images. For this discussion please see Franck Pachot's essay in DOAG News:

https://www.doag.org/formes/servlet/DocNavi?action=getFile&did=6939790&file=2015-03-News-Franck_Pachot-Data-virtualization-playing-with-Oracle-12c-on-Docker-containers.pdf

**Comment by Djelibeybi** [comment]
First, the Oracle Linux is a fully supported production image. However, Oracle Database is not supported under Docker, regardless of platform. This has nothing to do with Oracle Linux and should be addressed to the Database team themselves.

However, the inability to set ulimit is not a restriction within the Oracle Linux image, but within Docker itself. You can't do it in any Docker container. For example, here's the official Docker-supplied Ubuntu container:

````
$ docker run --rm -t -i ubuntu /bin/bash
root@a945e764265d:/# ulimit -Hn 65536
bash: ulimit: open files: cannot modify limit: Invalid argument
````

However, the container should already have way higher a ulimit than you need:

````
$ docker run --rm -t -i oraclelinux /bin/bash
[root@21b7c00bda0c /]# ulimit -Hn
1048576
````

So, I'm going to close this issue.

**Comment by Djelibeybi** [comment]
For reference, here is a discussion on the docker-user mailing list about this same issue: https://groups.google.com/forum/#!topic/docker-user/T45Kc9vD804

**Comment by wkoertgen** [comment]
Thanks a lot, Avi, for your clarifications.

Am 24.09.2015 um 09:13 schrieb Avi Miller:
>
> For reference, here is a discussion on the docker-user mailing list 
> about this same issue: 
> https://groups.google.com/forum/#!topic/docker-user/T45Kc9vD804 
> <https://groups.google.com/forum/#%21topic/docker-user/T45Kc9vD804>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/oracle/docker/issues/28#issuecomment-142836519>.
>

-- 
Freundliche Grüsse / Kind Regards

Hans Werner Körtgen
DBLAB Körtgen
Sülzgürtel 86
D-50937 K ö l n

DEUTSCHLAND / GERMANY

Mobile: +49 162 6272476 (NEU !)
Blog: wkoertgen.blogspot.de
