### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by buttso** [oracle/docker#3]
I'm not sure the description of this project isn't fully correct.  

It doesn't provide images per-se - there's nothing I can download and directly import as a docker image.

What it does it provide a project that produce a docker image, once the relevant binary distributions have been downloaded and copied into the project and the buildDockerImage script executed.

**Comment by Djelibeybi** [comment]
The project description has been recently updated to be more accurate, but the repo does store Oracle Linux images (in the OracleLInux-images branch) which are imported into the Docker Hub Registry. We've also renamed the repository to "docker" to be more accurate.

**Comment by buttso** [comment]
>>This repository stores Docker images for Oracle products.

The master branch contains OracleWebLogic and OracleCoherence folders which don't provide docker images that can be downloaded and used.  They need to be actioned to produce an image.  Just pointing that out since they are the immediately visible items seen.  The description could note that this repo stored Docker images for OracleLinux and Docker configuration projects for WebLogic and Coherence.

**Comment by Djelibeybi** [comment]
The description is now: "Official source for Docker configurations, images, and examples of Dockerfiles for Oracle products"

Note that we expect more Oracle products to arrive in the repo over time.

**Comment by buttso** [comment]
Cool thanks - this is a great initiative.
