### ISSUE TITLE
Stale object in .git taking up 203MB

### ISSUE THREAD

**Issue by derekmwright** [oracle/docker#30]
.git/objects/pack$ ls -lh                                                                                                                                                               master 
total 203M
-r--r--r--. 1 user group  23K Sep 25 14:01 pack-b1813bd685222dd05abacc315057a384962cf448.idx
-r--r--r--. 1 user group 203M Sep 25 14:01 pack-b1813bd685222dd05abacc315057a384962cf448.pack

The only way I know of to get rid of this on the remote is to clean the artifact out of the local repo - delete the remote and then push this back up to the remote. This is a rather large repo to clone for a few text files because of this.

**Comment by Djelibeybi** [comment]
It's not just a few text files. If you switch to the `OracleLinux-images` branch, you'll find several large binary tarballs (40MB-60MB each) which are the root filesystem sources for the official Oracle Linux images on the Docker Hub.

**Comment by derekmwright** [comment]
Gotcha, it was a hefty clone. Thanks for the response.
