### ISSUE TITLE
buildDockerImage

### ISSUE THREAD

**Issue by jedi132000** [oracle/docker#31]
I am having issues running the build script, please help!!

![dockerbuild](https://cloud.githubusercontent.com/assets/14984442/10439425/cf8d26d6-7107-11e5-9132-c9b4cd0be972.PNG)

**Comment by Djelibeybi** [comment]
You haven't downloaded the required components from Oracle. You need to download WebLogic and Java first.

**Comment by Djelibeybi** [comment]
Check the .download files in the repository. They tell you where to download the actual components from.

**Comment by jedi132000** [comment]
See the image below

![image](https://cloud.githubusercontent.com/assets/14984442/10439726/f4bd5262-7109-11e5-8bca-da596a964bf0.png)

**Comment by Djelibeybi** [comment]
Exactly. You are missing the actual files. The .download files are placeholders that contain instructions that point to where to download the actual binaries from Oracle for FMW, WLS and Java.

**Comment by jedi132000** [comment]
Thanks

**Comment by jedi132000** [comment]
Having this issue, any suggestions.
![image](https://cloud.githubusercontent.com/assets/14984442/10441800/cdfd45ae-711a-11e5-9b4b-878803df7f61.png)

**Comment by Djelibeybi** [comment]
First, it would be much better for you to cut and paste the errors into GitHub, rather than having to read a screenshot.

Second, it looks like you're running out of memory trying to start WebLogic. Please open another issue for this (with the actual error pasted, not a screenshot, please). I'll then assign that to the WLS guys.

**Comment by jedi132000** [comment]
Ok, thanks for the timely response.
I have resized my server but i am still getting an Error starting weblogic 

"[8] System error: exec: "startWeblogic.sh": executable file not found in $PATH"

**Comment by Djelibeybi** [comment]
As I mentioned above, this is an unrelated issue. Please open a new issue and paste the entire output, including the error, for better support.
