### ISSUE TITLE
Starting Weblogic 

### ISSUE THREAD

**Issue by jedi132000** [oracle/docker#32]
I am trying to start weblogic but running into issues.

oladimeji@TrainingServer:~/test/docker/OracleWebLogic/samples/12c-domain$ docker run -d -p 8001:8001 --name=AdminServer  samplewls:12.1.3 startWeblogic.sh
c5216eac91034f606330305fb2b8febd9f127237ca999d86006be23bbf07133a
Error response from daemon: Cannot start container c5216eac91034f606330305fb2b8febd9f127237ca999d86006be23bbf07133a: [8] System error: exec: "startWeblogic.sh": executable file not found in $PATH

**Comment by jedi132000** [comment]
Any pointers or updates?

**Comment by Djelibeybi** [comment]
This is not an official support channel. If you have Oracle Support for WebLogic, you can open a Support Request via My Oracle Support at https://support.oracle.com.

Otherwise, you'll have to wait until @brunoborges can review this issue.

**Comment by jedi132000** [comment]
ok, will do.

**Comment by brunoborges** [comment]
The script is called startWebLogic.sh (with capital L). Try that. Linux is case-sensitive.

**Comment by jedi132000** [comment]
Thank you, it ran 
but the admin console is not coming up.
[http://xxx.xx.x.xx:8001/console](http://xxx.xx.x.xx:8001/console).

from the read me, do i have to enter it exactly as above  wih the brackets and all that or
just
http://xxx.xx.x.xx:8001/console.

i used several types of browsers.

**Comment by jedi132000** [comment]
[http://xxx.xx.x.xx:8001/console](http://xxx.xx.x.xx:8001/console).

**Comment by brunoborges** [comment]
It will depend on how you are actually running the container and how you are configuring the network of your container. Try to attach port 8001 to your host, at 8001 too, then access it as http://localhost:8001/console

**Comment by jedi132000** [comment]
sudo docker run -d -p 8001:8001 --name=wlsadmin samplewls:12.1.3 startWebLogic.sh
sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' wlsadmin
got the IP 
and tried to access the URL
how do i attach a port to the localhost please advise.

**Comment by brunoborges** [comment]
Please check Docker documentation for details on how to properly attach ports to host environment.

Issue closed.

**Comment by jedi132000** [comment]
oladimeji@TrainingServer:~/test/docker/OracleWebLogic$ docker run -d -p 8001:8001 --name=WlsAdmin samplewls:12.1.3 startWebLogic.sh
5048f0bef96668c6a4721f573f86647749b5d11555d518dc34b48b6ddf639816
oladimeji@TrainingServer:~/test/docker/OracleWebLogic$ docker inspect --format '{{ .NetworkSettings.IPAddress }}' WlsAdmin
172.17.0.26

I understand this isn't a support channel, but i am yet to access the weblogic console.
so i cannot consider it closed

**Comment by brunoborges** [comment]
You are facing Docker networking issues, nothing related to WebLogic. Again, attach the port 8001 to the host, open the browser (on your host) and just go to http://localhost:8001/console

**Comment by jedi132000** [comment]
WLS 12.1.3. up and running and i can access the console.
Appreciate the patience and support

**Comment by jedi132000** [comment]
docker run  -p xx.xx.xx.xx:8001:8001 --name=wlsadmin  -t samplewls:12.1.3
docker command for attaching port
hope it helps

**Comment by raisercostin** [comment]
I had the same problem ("startWeblogic.sh": executable file not found in $PATH) and found that in my case I started server (FROM oracle/weblogic:12.1.3-developer) instead of a domain (FROM 1213-domain).

**Comment by amitvanjani** [comment]
Hi Jedi, What is this xx.xx.xx.xx IP in your command?

**Comment by amitvanjani** [comment]
I have started my weblogic domain using below command on docker terminal
docker run -d --name=wlsadmin -p 8001:8001 1221-domain

Container is running. But when I try to access http://localhost:8001/console on my windows where docker client is running the link doesnt work.

**Comment by amitvanjani** [comment]
I followed below steps and it started working:

$ docker-machine ip
xx.xx.xx.xx
This gives me my docker machine IP, which I will use in below command.

$ docker run -d --name=wlsadmin -p xx.xx.xx.xx:8001:8001 1221-domain

After running above command, I opened google chrome and instead of using localhost. i used this console URL - http://xx.xx.xx.xx:8001/console and it works.

**Comment by zraidihassan** [comment]
revolved also by change the config.xml in your domain and make commit of your container .
 <server>
    <name>AdminServer</name>
    <listen-address>localhost</listen-address>
  </server>

just remove the localhost entry
