### ISSUE TITLE
jaxrs2 template not updated for new 12.2.1 samples

### ISSUE THREAD

**Issue by hermith** [oracle/docker#38]
jaxrs2 deployment fails because the template has not been updated.

`template-info.xml` only needs to have ` version="12.1.3.0.0"`changed to to ` version="12.2.1.0.0"` 
`config/config.xml` needs to change:

    <domain-version>12.1.3.0.0</domain-version>
    <configuration-version>12.1.3.0.0</configuration-version>
    <library>
      <name>jax-rs#2.0@2.5.1</name>
to:

    <domain-version>12.2.1.0.0</domain-version>
    <configuration-version>12.2.1.0.0</configuration-version>
    <library>
      <name>jax-rs#2.0@2.21.1.0</name>

When I updated this in the jar file jaxrs successfully deployed again.

**Comment by brunoborges** [comment]
No need for JAX-RS since WLS 12.2.1 is Java EE 7 certified. This issue has been fixed by PR #37
