### ISSUE TITLE
Provide based docker images in docker hub

### ISSUE THREAD

**Issue by rodlogic** [oracle/docker#41]
These scripts are nice, specially the ones to create custom domains on top of the base images, but it would be even simpler if these images were created and uploaded by you directly to docker hub or your registry of choice.

**Comment by Djelibeybi** [comment]
These images cannot be uploaded to the Docker Hub because they require Oracle proprietary software which requires the acceptance of the Oracle license terms prior to download/use.

We are investigating our own Oracle Docker Registry but this has no ETA.
