### ISSUE TITLE
Is there are way to reduce the image size?

### ISSUE THREAD

**Issue by rodlogic** [oracle/docker#42]
I have built this locally and have an image with 1.7Gb. When I am basically interested in running development domains on Weblogic this becomes a drag across the team.

**Comment by Djelibeybi** [comment]
I'm not sure if there's a way to reduce the overall size, hence I'm assigning this to @brunoborges. However, if you use `btrfs` as your storage option, Docker will automatically create subvolumes for each layer and reuse them across containers.

**Comment by brunoborges** [comment]
The scripts provided here are starters, that users can use to kick off their WebLogic on Docker deployments. Our certification and support is over the topologies as described in the [whitepaper](http://www.oracle.com/technetwork/middleware/weblogic/overview/weblogic-server-docker-containers-2491959.pdf) and related documentation. 

Users are free to use different Docker techniques to achieve better image size compression if they want, such as what @Djelibeybi suggests, as well custom Dockerfiles that may save greater speace.
