### ISSUE TITLE
stat wls1213_dev_update3.zip: no such file or directory

### ISSUE THREAD

**Issue by rogerhill01234** [oracle/docker#44]
I am trying to install docker container for WebLogic 12.1.3 but getting into an error:

stat wls1213_dev_update3.zip: no such file or directory
There was an error building the image.

Here is the full log of the execution:

$ sh buildDockerImage.sh -v 12.1.3 -d
=====================
Building image 'oracle/weblogic:12.1.3-dev' based on 'developer' distribution...
Sending build context to Docker daemon 22.02 kB
Step 1 : FROM oraclelinux:7
Pulling repository docker.io/library/oraclelinux
a8fd27de55f5: Download complete
8c3e49cb06dc: Download complete
8a322a55d96f: Download complete
Status: Downloaded newer image for oraclelinux:7
docker.io/library/oraclelinux: this image was pulled from a legacy registry.  Important: This registry version will not be support
ed in future versions of docker.
 ---> a8fd27de55f5
Step 2 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
 ---> Running in 8f0f8f5a0ac3
 ---> 9a7543f6d925
Removing intermediate container 8f0f8f5a0ac3
Step 3 : ENV JAVA_RPM jdk-8u60-linux-x64.rpm
 ---> Running in e4a0dd7a96b4
 ---> c855ee151d2c
Removing intermediate container e4a0dd7a96b4
Step 4 : ENV WLS_PKG wls1213_dev_update3.zip
 ---> Running in ae53148ed844
 ---> 9e950c584004
Removing intermediate container ae53148ed844
Step 5 : ENV JAVA_HOME /usr/java/default
 ---> Running in 2dc918177c4f
 ---> 0684153769e8
Removing intermediate container 2dc918177c4f
Step 6 : ENV MW_HOME /u01/oracle/wls12130
 ---> Running in 657abb887d36
 ---> 438841df6c38
Removing intermediate container 657abb887d36
Step 7 : ENV CONFIG_JVM_ARGS -Djava.security.egd=file:/dev/./urandom
 ---> Running in c0f4ad2664e3
 ---> 49bafda5511b
Removing intermediate container c0f4ad2664e3
Step 8 : ENV JAVA_OPTIONS -Djava.security.egd=file:/dev/./urandom
 ---> Running in c794ca595882
 ---> 1d8ac2fa885c
Removing intermediate container c794ca595882
Step 9 : RUN mkdir /u01 && chmod a+xr /u01 &&     useradd -b /u01 -m -s /bin/bash oracle
 ---> Running in a170f6fe6790
 ---> 3e98517ac372
Removing intermediate container a170f6fe6790
Step 10 : COPY $WLS_PKG /u01/
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
stat wls1213_dev_update3.zip: no such file or directory
There was an error building the image.

Any insights and suggestions are highly appreciated.

**Comment by Djelibeybi** [comment]
Have you downloaded wls1213_dev_update3.zip from OTN? It's not included, you need to download it manually.

**Comment by Djelibeybi** [comment]
Double check the README for more info: https://github.com/oracle/docker/blob/master/OracleWebLogic/README.md

**Comment by brunoborges** [comment]
Thanks Avi @Djelibeybi =)
