### ISSUE TITLE
Cannot reach admin console after launching image

### ISSUE THREAD

**Issue by rogerhill01234** [oracle/docker#46]
I have been able to launch WL server following the instructions in the git page. But when I connect to the console, i get a "connection refused" error. (I am running the docker container on Windows)

$ docker ps -l
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                          NAMES
08e88ed803c7        samplewls:12.1.3    "startWebLogic.sh"   31 minutes ago      Up 31 minutes       5556/tcp, 7001/tcp, 8001/tcp   wlsadmin

$ docker-machine ip default
192.168.99.100

$ curl http://192.168.99.100:8001/console
curl: (7) Failed to connect to 192.168.99.100 port 8001: Connection refused

Any thoughts? 
Thanks!

**Comment by brunoborges** [comment]
I see you are using Docker Machine. If you don't use Docker Machine, do you still face this issue? 

Can you please report the docker inspect of this container?

**Comment by rogerhill01234** [comment]
Here is the inspect of the container:

$ docker inspect wlsadmin
[
{
    "Id": "08e88ed803c70205464165f41fbc4a75bc2391c5d469cc15d80d89bf7e59d818",
    "Created": "2015-11-20T17:07:41.767577112Z",
    "Path": "startWebLogic.sh",
    "Args": [],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 16042,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-11-20T20:16:18.156253142Z",
        "FinishedAt": "2015-11-20T17:40:48.919443618Z"
    },
    "Image": "ff0a810814894e32af80866efb4da593830bf0376cdbe2a76c12b7f72d5bbc1f",
    "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/08e88ed803c70205464165f41fbc4a75bc2391c5d469cc15d80d89bf7e59d818/resolv.conf",
    "HostnamePath": "/mnt/sda1/var/lib/docker/containers/08e88ed803c70205464165f41fbc4a75bc2391c5d469cc15d80d89bf7e59d818/hostname",
    "HostsPath": "/mnt/sda1/var/lib/docker/containers/08e88ed803c70205464165f41fbc4a75bc2391c5d469cc15d80d89bf7e59d818/hosts",
    "LogPath": "/mnt/sda1/var/lib/docker/containers/08e88ed803c70205464165f41fbc4a75bc2391c5d469cc15d80d89bf7e59d818/08e88ed803c70205464165f41fbc4a75bc2391c5d469cc15d80d89bf7e59d818-json.log",
    "Name": "/wlsadmin",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            27,
            130
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [],
    "Config": {
        "Hostname": "08e88ed803c7",
        "Domainname": "",
        "User": "oracle",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "5556/tcp": {},
            "7001/tcp": {},
            "8001/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/u01/oracle/weblogic/oracle_common/common/bin:/u01/oracle/weblogic/wlserver/common/bin:/u01/oracle/weblogic/user_projects/domains/base_domain/bin:/u01/oracle",
            "JAVA_RPM=jdk-8u60-linux-x64.rpm",
            "WLS_PKG=wls1213_dev_update3.zip",
            "JAVA_HOME=/usr/java/default",
            "MW_HOME=/u01/oracle/wls12130",
            "CONFIG_JVM_ARGS=-Djava.security.egd=file:/dev/./urandom",
            "JAVA_OPTIONS=-Djava.security.egd=file:/dev/./urandom",
            "ADMIN_PASSWORD=welcome1",
            "ADMIN_PORT=8001",
            "NM_PORT=5556",
            "MS_PORT=7001",
            "USER_MEM_ARGS=-Xms256m -Xmx512m -XX:MaxPermSize=2048m"
        ],
        "Cmd": [
            "startWebLogic.sh"
        ],
        "Image": "samplewls:12.1.3",
        "Volumes": null,
        "WorkingDir": "/u01/oracle",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": {},
        "StopSignal": "15"
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "ebdb3c89e35a95490e642a3d4767761a75d205e6e445c67775f2ddcb48de9176",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "5556/tcp": null,
            "7001/tcp": null,
            "8001/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/ebdb3c89e35a",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "de37f86dc5dac322d1cdb7959110fcabefe473bd45198248eeb17bc7f4b32e8d",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:02",
        "Networks": {
            "bridge": {
                "EndpointID": "de37f86dc5dac322d1cdb7959110fcabefe473bd45198248eeb17bc7f4b32e8d",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:02"
            }
        }
    }
}
]

**Comment by rogerhill01234** [comment]
I am not sure how you can avoid using docker machine. Docker machine is just an instance of docker daemon as I understand. I have only one daemon running. 

$ docker-machine ls
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM
default    *        virtualbox   Running   tcp://192.168.99.100:2376
machine1   -        virtualbox   Stopped

**Comment by Djelibeybi** [comment]
Docker Machine is a way to manage instances of the Docker Engine. In this case, it's created a VirtualBox VM on your host and is running Docker inside that VM. This creates additional network complexities that you wouldn't see on a Linux box that's running `docker-engine` natively.

**Comment by rogerhill01234** [comment]
The additional complexity is in getting the IP address of the virtual host instead of the localhost. Right? That is why I am using the IP address of the Virtual Box VM. I am able to get to the port of a simple application:

$ docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                          NAMES
70772dd144cf        training/webapp     "python app.py"      6 seconds ago       Up 4 seconds        0.0.0.0:80->5000/tcp           web
08e88ed803c7        samplewls:12.1.3    "startWebLogic.sh"   3 hours ago         Up 3 minutes        5556/tcp, 7001/tcp, 8001/tcp   wlsadmin

$ curl http://192.168.99.100:80/
Hello world!

$ curl http://192.168.99.100:8001/console
curl: (7) Failed to connect to 192.168.99.100 port 8001: Connection refused

$ docker logs -f wlsadmin
.***
<Nov 20, 2015 8:27:45 PM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to RESUMING.>
<Nov 20, 2015 8:27:46 PM GMT> <Notice> <Server> <BEA-002613> <Channel "Default" is now listening on 172.17.0.2:8001 for protocols iiop, t3, ldap, snmp, http.>
<Nov 20, 2015 8:27:46 PM GMT> <Notice> <Server> <BEA-002613> <Channel "Default[3]" is now listening on 127.0.0.1:8001 for protocols iiop, t3, ldap, snmp, http.>
<Nov 20, 2015 8:27:46 PM GMT> <Notice> <Server> <BEA-002613> <Channel "Default[2]" is now listening on 0:0:0:0:0:0:0:1:8001 for protocols iiop, t3, ldap, snmp, http.>
<Nov 20, 2015 8:27:46 PM GMT> <Notice> <Server> <BEA-002613> <Channel "Default[1]" is now listening on fe80:0:0:0:42:acff:fe11:2:8001 for protocols iiop, t3, ldap, snmp, http.>
<Nov 20, 2015 8:27:46 PM GMT> <Notice> <WebLogicServer> <BEA-000329> <Started the WebLogic Server Administration Server "AdminServer" for domain "base_domain" running in production mode.>
<Nov 20, 2015 8:27:46 PM GMT> <Warning> <Server> <BEA-002611> <The hostname "localhost", maps to multiple IP addresses: 127.0.0.1, 0:0:0:0:0:0:0:1.>
<Nov 20, 2015 8:27:46 PM GMT> <Notice> <WebLogicServer> <BEA-000360> <The server started in RUNNING mode.>
<Nov 20, 2015 8:27:46 PM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to RUNNING.>

I can ping the VM host IP address:

$ ping 192.168.99.100

Pinging 192.168.99.100 with 32 bytes of data:
Reply from 192.168.99.100: bytes=32 time<1ms TTL=64
Reply from 192.168.99.100: bytes=32 time<1ms TTL=64
Reply from 192.168.99.100: bytes=32 time<1ms TTL=64
Reply from 192.168.99.100: bytes=32 time<1ms TTL=64

Ping statistics for 192.168.99.100:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

**Comment by rogerhill01234** [comment]
I found a difference between the python app and weblogic. The inspect of weblogic app:

    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "ebdb3c89e35a95490e642a3d4767761a75d205e6e445c67775f2ddcb48de9176",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "5556/tcp": null,
            "7001/tcp": null,
            "8001/tcp": null
        },

The inspect of python app:

   "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "8b0afc5c668a7452197b5599fcc6f62513c8e0138a622d315efd8f679257ee68",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "5000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "80"
                }
            ]
        },

As you can see the ports in weblogic are not mapped to host ports.

**Comment by rogerhill01234** [comment]
I ran the python app container with out port mapping (-P or -p options):
$ docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                          NAMES
d47d453179a6        training/webapp     "python app.py"      17 seconds ago      Up 16 seconds       5000/tcp                       web
08e88ed803c7        samplewls:12.1.3    "startWebLogic.sh"   3 hours ago         Up 17 minutes       5556/tcp, 7001/tcp, 8001/tcp   wlsadmin

$ curl http://192.168.99.100:5000/
curl: (7) Failed to connect to 192.168.99.100 port 5000: Connection refused

And the corresponding inspect for python app container is: 
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "cbe856fc3b9933a2ef8f32dd3515404397272947a50bfaa0e3361e02c94aa561",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "5000/tcp": null
        },

which shows the port number mapping to be null just as in weblogic's. I think if the port mapping is specified everything should work fine. 

So if I add the -P option:

$  docker run -d -P --name=wlsadmin samplewls:12.1.3
71e1f35728c03d1b45fa8e1fb29f552c7664bfad1ac9202498a74a6dda5cdf44

$ docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS
                           NAMES
71e1f35728c0        samplewls:12.1.3    "startWebLogic.sh"   14 seconds ago      Up 12 seconds       0.0.0.0:32770->5556/tcp, 0.0.0.0:32769->7001/tcp,
 0.0.0.0:32768->8001/tcp   wlsadmin
d47d453179a6        training/webapp     "python app.py"      6 minutes ago       Up 6 minutes        5000/tcp
                           web

$ curl http://192.168.99.100:32768/console
<html><head><title>302 Moved Temporarily</title></head>
<body bgcolor="#FFFFFF">
<p>This document you requested has moved
temporarily.</p>
<p>It's now at <a href="http://192.168.99.100:32768/console/">http://192.168.99.100:32768/console/</a>.</p>
</body></html>

it works! I think the git documentation should be updated to include this option (-P option). 

Thanks for the quick responses Bruno and Avi - you got me moving forward.

**Comment by brunoborges** [comment]
It is always related to how you configure the network setting of the container. Docs are not very specific because there aRe many ways to setup that.

Glad you found out :)
