### ISSUE TITLE
Step 14: scriptlet failed, exit status 2

### ISSUE THREAD

**Issue by rekdt** [oracle/docker#47]
Hello,

While building the image with sudo sh buildDockerImage.sh -v 12.2.1 -d I get an error on step 14. However, the image continues to build and says successful. But when I try to build a weblogic instance and boot up the container, it doesn't come up. There is no error, the container just never runs. This is the only error I see that might be related. 

Step 14 : RUN rpm -i /u01/$JAVA_RPM &&     rm /u01/$JAVA_RPM
 ---> Running in 64a1a3d1f799
Unpacking JAR files...
 tools.jar...
 plugin.jar...
 javaws.jar...
 deploy.jar...
 rt.jar...
 jsse.jar...
 charsets.jar...
 localedata.jar...
 jfxrt.jar...
failed to link /usr/share/man/man1/java.1 -> /etc/alternatives/java.1: No such file or directory
failed to link /usr/share/man/man1/javaws.1 -> /etc/alternatives/javaws.1: No such file or directory
failed to link /usr/share/man/man1/jjs.1 -> /etc/alternatives/jjs.1: No such file or directory
failed to link /usr/share/man/man1/keytool.1 -> /etc/alternatives/keytool.1: No such file or directory
failed to link /usr/share/man/man1/orbd.1 -> /etc/alternatives/orbd.1: No such file or directory
failed to link /usr/share/man/man1/pack200.1 -> /etc/alternatives/pack200.1: No such file or directory
failed to link /usr/share/man/man1/policytool.1 -> /etc/alternatives/policytool.1: No such file or directory
failed to link /usr/share/man/man1/rmid.1 -> /etc/alternatives/rmid.1: No such file or directory
failed to link /usr/share/man/man1/rmiregistry.1 -> /etc/alternatives/rmiregistry.1: No such file or directory
failed to link /usr/share/man/man1/servertool.1 -> /etc/alternatives/servertool.1: No such file or directory
failed to link /usr/share/man/man1/tnameserv.1 -> /etc/alternatives/tnameserv.1: No such file or directory
failed to link /usr/share/man/man1/unpack200.1 -> /etc/alternatives/unpack200.1: No such file or directory
failed to link /usr/share/man/man1/appletviewer.1 -> /etc/alternatives/appletviewer.1: No such file or directory
failed to link /usr/share/man/man1/extcheck.1 -> /etc/alternatives/extcheck.1: No such file or directory
failed to link /usr/share/man/man1/idlj.1 -> /etc/alternatives/idlj.1: No such file or directory
failed to link /usr/share/man/man1/jar.1 -> /etc/alternatives/jar.1: No such file or directory
failed to link /usr/share/man/man1/jarsigner.1 -> /etc/alternatives/jarsigner.1: No such file or directory
failed to link /usr/share/man/man1/java.1 -> /etc/alternatives/java.1: No such file or directory
failed to link /usr/share/man/man1/javac.1 -> /etc/alternatives/javac.1: No such file or directory
failed to link /usr/share/man/man1/javadoc.1 -> /etc/alternatives/javadoc.1: No such file or directory
failed to link /usr/share/man/man1/javafxpackager.1 -> /etc/alternatives/javafxpackager.1: No such file or directory
failed to link /usr/share/man/man1/javah.1 -> /etc/alternatives/javah.1: No such file or directory
failed to link /usr/share/man/man1/javap.1 -> /etc/alternatives/javap.1: No such file or directory
failed to link /usr/share/man/man1/javapackager.1 -> /etc/alternatives/javapackager.1: No such file or directory
failed to link /usr/share/man/man1/javaws.1 -> /etc/alternatives/javaws.1: No such file or directory
failed to link /usr/share/man/man1/jcmd.1 -> /etc/alternatives/jcmd.1: No such file or directory
failed to link /usr/share/man/man1/jconsole.1 -> /etc/alternatives/jconsole.1: No such file or directory
failed to link /usr/share/man/man1/jdb.1 -> /etc/alternatives/jdb.1: No such file or directory
failed to link /usr/share/man/man1/jdeps.1 -> /etc/alternatives/jdeps.1: No such file or directory
failed to link /usr/share/man/man1/jhat.1 -> /etc/alternatives/jhat.1: No such file or directory
failed to link /usr/share/man/man1/jinfo.1 -> /etc/alternatives/jinfo.1: No such file or directory
failed to link /usr/share/man/man1/jjs.1 -> /etc/alternatives/jjs.1: No such file or directory
failed to link /usr/share/man/man1/jmap.1 -> /etc/alternatives/jmap.1: No such file or directory
failed to link /usr/share/man/man1/jmc.1 -> /etc/alternatives/jmc.1: No such file or directory
failed to link /usr/share/man/man1/jps.1 -> /etc/alternatives/jps.1: No such file or directory
failed to link /usr/share/man/man1/jrunscript.1 -> /etc/alternatives/jrunscript.1: No such file or directory
failed to link /usr/share/man/man1/jsadebugd.1 -> /etc/alternatives/jsadebugd.1: No such file or directory
failed to link /usr/share/man/man1/jstack.1 -> /etc/alternatives/jstack.1: No such file or directory
failed to link /usr/share/man/man1/jstat.1 -> /etc/alternatives/jstat.1: No such file or directory
failed to link /usr/share/man/man1/jstatd.1 -> /etc/alternatives/jstatd.1: No such file or directory
failed to link /usr/share/man/man1/jvisualvm.1 -> /etc/alternatives/jvisualvm.1: No such file or directory
failed to link /usr/share/man/man1/keytool.1 -> /etc/alternatives/keytool.1: No such file or directory
failed to link /usr/share/man/man1/native2ascii.1 -> /etc/alternatives/native2ascii.1: No such file or directory
failed to link /usr/share/man/man1/orbd.1 -> /etc/alternatives/orbd.1: No such file or directory
failed to link /usr/share/man/man1/pack200.1 -> /etc/alternatives/pack200.1: No such file or directory
failed to link /usr/share/man/man1/policytool.1 -> /etc/alternatives/policytool.1: No such file or directory
failed to link /usr/share/man/man1/rmic.1 -> /etc/alternatives/rmic.1: No such file or directory
failed to link /usr/share/man/man1/rmid.1 -> /etc/alternatives/rmid.1: No such file or directory
failed to link /usr/share/man/man1/rmiregistry.1 -> /etc/alternatives/rmiregistry.1: No such file or directory
failed to link /usr/share/man/man1/schemagen.1 -> /etc/alternatives/schemagen.1: No such file or directory
failed to link /usr/share/man/man1/serialver.1 -> /etc/alternatives/serialver.1: No such file or directory
failed to link /usr/share/man/man1/servertool.1 -> /etc/alternatives/servertool.1: No such file or directory
failed to link /usr/share/man/man1/tnameserv.1 -> /etc/alternatives/tnameserv.1: No such file or directory
failed to link /usr/share/man/man1/unpack200.1 -> /etc/alternatives/unpack200.1: No such file or directory
failed to link /usr/share/man/man1/wsgen.1 -> /etc/alternatives/wsgen.1: No such file or directory
failed to link /usr/share/man/man1/wsimport.1 -> /etc/alternatives/wsimport.1: No such file or directory
failed to link /usr/share/man/man1/xjc.1 -> /etc/alternatives/xjc.1: No such file or directory
warning: %post(jdk1.8.0_60-2000:1.8.0_60-fcs.x86_64) scriptlet failed, exit status 2

**Comment by brunoborges** [comment]
Please verify that you have downloaded all required files.

**Comment by javabrett** [comment]
This can occur on a very slim image, such as a Docker base image, which is missing the `filesystem` package, or is otherwise missing `/usr/share/man/man1`.  A simple `mkdir -p /usr/share/man/man1` before adding the JDK RPM will fix this - the JDK RPM postinstall scriptlet expects this directory to be present.
