### ISSUE TITLE
Wrong files name

### ISSUE THREAD

**Issue by rdgacarvalho** [oracle/docker#48]
The name of requirement files are wrong, sample:
-rw-r--r-- 1 root root  229 Nov 25 11:08 fmw_12.1.3.0.0_wls.jar.download
-rw-r--r-- 1 root root 1272 Nov 25 11:08 install.file
-rw-r--r-- 1 root root  191 Nov 25 11:08 jdk-8u60-linux-x64.rpm.download
-rw-r--r-- 1 root root   55 Nov 25 11:08 oraInst.loc
-rw-r--r-- 1 root root  384 Nov 25 11:08 wls1213_dev_update3.zip.download

When the build script try build a new images with files without the string download end of each file.

**Comment by brunoborges** [comment]
They are called .download because you have to download them first. Those are placeholders.
