### ISSUE TITLE
Wrong sample port number in README.md

### ISSUE THREAD

**Issue by ufoscout** [oracle/docker#50]
In the OracleWebLogic/README.md file is written that the samplewls:12.1.3 docker image starts a WL console at the port 8001. However, in other places of the same document the console is associated with the port 7001. Sometimes the two different port numbers are used in the same sentence, e.g.:

'''
Now you can access the AdminServer Web Console at http://172.17.0.27:7001/console. You can also access it locally if you bind port 8001 to your host, with -p 8001:8001.
'''

**Comment by brunoborges** [comment]
Thanks @ufoscout. It has been fixed.
