### ISSUE TITLE
Container start fails with missing  /usr/bin/my_print_defaults reference from entrypoint.sh

### ISSUE THREAD

**Issue by sardak** [oracle/docker#9]
I built the MySQL 5.5 image and tried to start it with the command:

    docker run --name=mysql -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root oracle/mysql:5.7 /entrypoint.sh mysqld

The mysql process doesn't start and when I do a "docker logs mysql" I get the following error:

    /entrypoint.sh: line 8: /usr/bin/my_print_defaults: No such file or directory

**Comment by Djelibeybi** [comment]
I have notified the MySQL team of this issue. Though, there seems to be a confusion between your statement and the command. You mention MySQL 5.5, but you're running oracle/mysql:5.7.

Finally, do you have the full output of the initial build of the container? My guess is that the yum command that actually installs MySQL from our repositories is failing, so the binaries are not being properly installed by the time the entrypoint script runs.

**Comment by sardak** [comment]
Hi Djelibeybi,

I get the issue on both 5.5 and 5.7. I don't think the yum command is failing because I tried downloading the artifact locally and changing the Dockerfile to use it.

Rather, I think the issue lies with the entrypoint.sh script.

On line 8 you have:

    ret=$(/usr/bin/my_print_defaults $section | grep '^--'${option}'=' | cut -d= -f2-)

I checked in the container, there's no `/usr/bin/my_print_defaults` command.

**Comment by Djelibeybi** [comment]
The MySQL Dockerfiles and entrypoint scripts have been updated with the latest from the MySQL team. Please download the latest version and try again.
